addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtPlugin("org.scalatra.sbt" % "scalatra-sbt" % "0.4.0")
addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "1.1.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.3")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")